#!/bin/bash

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="5.10.160-rockchip-rk356x" --arg="/boot/vmlinuz-5.10.160-rockchip-rk356x" /etc/kernel/postrm.d
exit 0
